docs: &docs
  - "**/*.md"
  - "docs/**"

backend: &backend
  - "**/*.go"
  - "**/*.tmpl"
  - "go.mod"
  - "go.sum"

frontend: &frontend
  - "**/*.js"
  - "web_src/**"
  - "package.json"
  - "package-lock.json"
