kind/docs:
  - "**/*.md"
  - "docs/**"

kind/ui:
  - "web_src/**/*"
  - all: ["templates/**", "!templates/swagger/v1_json.tmpl"]

kind/api:
  - "templates/swagger/v1_json.tmpl"
  - "routers/api/**"

kind/build:
  - "Makefile"
  - "Dockerfile"
  - "Dockerfile.rootless"
  - "docker/**"
  - "webpack.config.js"

theme/package-registry:
  - "modules/packages/**"
  - "services/packages/**"
  - "routers/api/packages/**"
  - "routers/web/shared/packages/**"

kind/cli:
  - "cmd/**"

kind/lint:
  - ".eslintrc.yaml"
  - ".golangci.yml"
  - ".markdownlint.yaml"
  - ".spectral.yaml"
  - ".stylelintrc.yaml"
  - ".yamllint.yaml"
