extends: stylelint-config-standard

plugins:
  - stylelint-declaration-strict-value

overrides:
  - files: ["**/*.less"]
    customSyntax: postcss-less
  - files: ["**/*.less"]
    rules:
      scale-unlimited/declaration-strict-value: [color, {
        ignoreValues: /^(inherit|transparent|unset|initial)$/
      }]
  - files: ["**/chroma/*", "**/codemirror/*", "**/standalone/*", "**/console/*"]
    rules:
      scale-unlimited/declaration-strict-value: null

rules:
  alpha-value-notation: null
  at-rule-empty-line-before: null
  block-closing-brace-empty-line-before: null
  color-function-notation: null
  color-hex-length: null
  comment-empty-line-before: null
  declaration-block-no-redundant-longhand-properties: null
  declaration-block-single-line-max-declarations: null
  declaration-empty-line-before: null
  function-no-unknown: null
  hue-degree-notation: null
  import-notation: string
  indentation: 2
  max-line-length: null
  no-descending-specificity: null
  no-invalid-position-at-import-rule: null
  number-leading-zero: never
  number-max-precision: null
  property-no-vendor-prefix: null
  rule-empty-line-before: null
  selector-class-pattern: null
  selector-id-pattern: null
  selector-pseudo-element-colon-notation: double
  shorthand-property-no-redundant-values: true
  string-quotes: null
  value-no-vendor-prefix: null
