name: "Cron: Update licenses and gitignores"

on:
  schedule:
    # weekly on Monday at 0:07 UTC
    - cron: "7 0 * * 1"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
      - name: update licenses and gitignores
        run: timeout -s ABRT 40m make generate-license generate-gitignore
      - name: push translations to repo
        uses: appleboy/git-push-action@v0.0.2
        with:
          author_email: "teabot@gitea.io"
          author_name: GiteaBot
          branch: main
          commit: true
          commit_message: "[skip ci] Updated licenses and gitignores"
          remote: "git@github.com:go-gitea/gitea.git"
          ssh_key: ${{ secrets.DEPLOY_KEY }}
